modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="Ti Works: All rights reserved"
#issueTrackerURL="https://?/" #optional
[[mods]] #mandatory
modId="terrariamod" #mandatory
version="0.0.2" #mandatory
displayName="Terraria Mod" #mandatory
#updateJSONURL="https://?/updates.json" #optional
displayURL="https://www.bilibili.com/video/BV1GJ411x7h7/" #optional
logoFile="Terraria.png" #optional
credits="Let's make Minecraft better." #optional
authors='''Ti works almost all
Maker coding and leading the group.
Kether setting rules and weigh playability for the mod and check performance.''' #optional
#mandatory
description='''
Terraria Mod!
Still work on!
In 0.0.1 we upload from MC1.18.1-Tl0.0.15
This time we add a great mana-system, we will try to change the mana GUI soon.(maybe 10 of round)
!This version still has its problem , waiting for more~
(ps:You absolutely not want to know what was stored in the website up there.)
'''
[[dependencies.terrariamod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.terrariamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19.1)"
    ordering="NONE"
    side="BOTH"
#Good evening, madam. Well...should I say now is midnight?---One forgotten night,0 O'clock. (Oh no! My hairs! :',D)